language: node_js

node_js:
  - '0.12'

services:
  - mongodb
  - elasticsearch

addons:
  postgresql: "9.3"

cache:
  directories:
    - node_modules
    - bower_components

notifications:
  email:
    - thibaultc@theodo.fr

before_install:
  - npm install -g npm@latest
  - createdb base_test
  - createuser pacman
  - psql -d base_test -c "ALTER DATABASE base_test OWNER TO pacman;"

before_script:
  - sleep 15
  - mongo base_test --eval 'db.addUser("pacman", "pacmanpass");'

script:
  - npm test

after_failure:
  - cat /home/travis/build/FastIT/health-check/npm-debug.log
