language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4.1'

services:
  - mongodb
  - elasticsearch

addons:
  postgresql: "9.3"

cache:
  directories:
    - node_modules
    - bower_components

notifications:
  email:
    - thibaultc@theodo.fr

before_install:
  - npm install -g npm@latest
  - createdb base_test
  - createuser pacman
  - psql -d base_test -c "ALTER DATABASE base_test OWNER TO pacman;"

before_script:
  - sleep 15
  - mongo testDb --eval 'db.addUser("pacman", "pacman");'

script:
  - npm test

after_failure:
  - cat /home/travis/build/FastIT/health-check/npm-debug.log

after_success:
  - cat coverage/lcov.info | COVERALLS_GIT_BRANCH=$TRAVIS_BRANCH COVERALLS_GIT_COMMIT=$TRAVIS_COMMIT ./node_modules/coveralls/bin/coveralls.js
