language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4.1'
  - '5.0'
  - '6.0'
  - '6.2'

notifications:
  email: false

cache:
  directories:
    - node_modules
    - bower_components

script:
  - npm test

after_success:
  - cat coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
