language: node_js

node_js:
  - '0.12'

services:
  - mongodb
  - elasticsearch

addons:
  postgresql: "9.3"

cache:
  directories:
    - node_modules
    - bower_components

notifications:
  email:
    - thibaultc@theodo.fr

before_install:
  - npm install -g npm@latest

before_script:
  - sleep 15
  - mongo testDb --eval 'db.addUser("pacman", "pacman");'
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - npm test

after_failure:
  - cat /home/travis/build/FastIT/health-check/npm-debug.log
